In [1]:
import numpy as np
import numpy.matlib as npm
import numpy.linalg as la
import scipy.special as ssp
import matplotlib.pyplot as plt
import scipy.integrate as si
import scipy.optimize as so

#import numpy as np

def konstruiere_Matrix(n,d,a,b,c):
    M=np.ones((n,n))*c
    for i in range(n):
        M[i][i]=d
    for i in range(n-1):
        M[i][i+1]=a
    for i in range(1, n):
        M[i][i-1]=b
    return M
print(konstruiere_Matrix(5, 100, 1, 999, -2))



print(bin(17), " ", bin(-20), " ", bin(32))
a=19
print(bin(a)[2:]) #2
print(oct(a)[2:]) #8
print(hex(a)[2:]) #16

b=bin(a)[2:]
n=1
ans=0
l=len(b)
for i in range(l):
    ans+=n*int(b[l-i-1])
    n*=2
print(ans)

[[100.   1.  -2.  -2.  -2.]
 [999. 100.   1.  -2.  -2.]
 [ -2. 999. 100.   1.  -2.]
 [ -2.  -2. 999. 100.   1.]
 [ -2.  -2.  -2. 999. 100.]]
0b10001   -0b10100   0b100000
10011
23
13
19


N1

N2

Tayloring a function

In [2]:
# Taylor-Funktion von cos(cx)
def cosT(x,c,n):
    ans=np.zeros(len(x))
    factorial=1
    for i in range(n+1):
        if(i>0):
            factorial=factorial*i;
        ans=ans + cosA(c,i) * (x**i) / factorial #cosA - ith derivative of cos
    return ans;

N3

Nullstellefunktion

In [3]:
#Nullstellensuchfunktion, die die reelle Nullstelle einer Funktion f(x) mittels des Sekantenverfahrens findet
#f - die Funktion, x1 - Anfangswert, fmin - minimum distance to be close enough to zero
def Nullstelle(f, x1, fmin):
    h_max=1
    it=0
    x2=x1+2*10**(-4)
    x3=x2
    while (np.abs(f(x3))>=fmin):
        it+=1
        #print(n, x0, x1, x2, f(x1), f(x2))
        x3=x2-f(x2)*(x2-x1)/(f(x2)-f(x1))
        if (x3-x2>h_max):
            x3=x2+1;
        if (x2-x3>h_max):
            x3=x2-1;
        x1=x2
        x2=x3
    return (x3, it)

#or

def N(f, x1):
    zero=sciopt.fsolve(f, x1, full_output="true")
    return zero
def N(f, x1):
    sciopt.fminbound(lambda x: np.abs(f(x)), -10, 10)
    return zero

N4

$F = (\vec v_{Sonne} ,\vec a_{Sonne},\vec v_{Erde} ,\vec a_{Erde},\vec v_{Mars} ,\vec a_{Mars})$

$\frac{d}{dt}  Y(t) =  F(t, Y(t))$

In [4]:
def Function (Y, t): 
    a_Sonne=np.multiply(np.subtract(r_E,r_S), G*m_Erde/(r_se**3))
    a_Erde=np.multiply(np.subtract(r_S,r_E), G/(r_se**3))
    a_Mars=np.multiply(np.subtract(r_S,r_M), G/(r_sm**3))
    
    for i in range(3):
        F[i]=Y[3+i]
        F[3+i]=a_Sonne[i]
        F[6+i]=Y[9+i]
        F[9+i]=a_Erde[i]
        F[12+i]=Y[15+i]
        F[15+i]=a_Mars[i]
    return F;

#or

def function(z, t): #hier z is F and we return an updated F
    return [z[1], -g-k*z[0]/m-b*z[1]/m];
def derivatives(t, y): #hier y is F and we return an updated F
    dydt = y[1]
    dvdt = -g-k*y[0]/m-b*y[1]/m
    return [dydt, dvdt]

def DGL(x_0, t):
    x=spin.odeint(function, x_0, t)

N5

Der Leapfrog Algorithmus:

$v_j(-\frac{\tau}{2})=v_j(0) - a_j(0)\frac{\tau}{2}$

$v_j(t+\frac{\tau}{2})=v_j(t-\frac{\tau}{2}) + a_j(t)\tau$

$r_j(t+\tau)=r_j(t) + v_j(t+\frac{\tau}{2}) \tau$

In [5]:
def solveDGL (T, r, t_tot=10, tau=0.001): # in K, Angström, ps, ps
    #Initial values
    t=np.arange(0, t_tot, tau)
    r1=np.zeros((len(t)))
    r2=np.zeros((len(t)))
    v0_1=np.sqrt(T/(2*m))
    v0_2=-v0_1
    r1[0]=0
    r2[0]=r
    
    v_minus_half_tau_1=v0_1 - a(-r)*tau/2 #a(x)=Force(x)/m
    v_minus_half_tau_2=v0_2 - a(r)*tau/2
    for i in range(0, len(t)-1):
        #Atom 1:
        v_plus_half_tau_1=v_minus_half_tau_1 + a(r1[i]-r2[i])*tau #a(x)=Force(x)/m
        r1[i+1]=r1[i] + v_plus_half_tau_1*tau
        v_minus_half_tau_1=v_plus_half_tau_1
        #Atom 2:
        v_plus_half_tau_2=v_minus_half_tau_2 + a(r2[i]-r1[i])*tau
        r2[i+1]=r2[i] + v_plus_half_tau_2*tau
        v_minus_half_tau_2=v_plus_half_tau_2
        
        #print(i, r1[i+1], r2[i+1])
        
    return(t, r1, r2)

N6

Trapezregel (n=1, 2 Stützpunkte):

$\int_a^b f(x) dx = \Sigma_{k=1}^N \frac{f(x_{k-1})+f(x_k)}{2}\Delta x_k =\frac{f(x_{0})+f(x_N)}{2} \Delta x + \Sigma_{k=1}^{N-1} f(x_k)\Delta x$

Die Simpson-Regel (n=2, 3 Stützpunkte):

$\int_a^b f(x) dx = \Sigma_{k=1}^N \frac{\Delta x_k}{3}(f(x_{k-1})+4f(x_{k-1}+h)+f(x_k))$

Boole-Regel (n=4, 5 Stützpunkte):

$\int_a^b f(x)dx = \Sigma_{k=1}^N \frac{2h}{45}(7f(x_{k-1})+32f(x_{k-1}+h)+12f(x_{k-1}+2h)+32f(x_{k-1}+3h)+7f(x_k))$

In [6]:
#f - the function we're integrating, [a, b] - the range, n - N in the sums above
def integrate (f,a,b,n,method):
    aufrufe=0
    if(method=="trapez"):
        x=np.linspace(a,b,n+1)
        delta_x=x[1]-x[0]
        res=-f(x[0])-f(x[n])
        res/=2
        for i in range(n+1):
            res+=f(x[i])
            aufrufe+=1
        res=res*delta_x
    if(method=="simpson"):
        H=(b-a)/n #H=2h
        res=0
        for i in range(n):
            x=np.linspace(a+i*H,a+(i+1)*H,3)
            res+=f(x[0])+4*f(x[1])+f(x[2])
            aufrufe+=3
        res=res*H/6 # h=H/2
    if(method=="bode"):
        H=(b-a)/n #H=4h
        res=0
        for i in range(n):
            x=np.linspace(a+i*H,a+(i+1)*H,5)
            res+=7*f(x[0])+32*f(x[1])+12*f(x[2])+32*f(x[3])+7*f(x[4])
            aufrufe+=5
        res=res*H/90 # h=H/4
    return res, aufrufe

N7

LU-Zerlegung

$b=Ax=(LU)x$

$b(p)=Ly$

$y=Ux$

In [7]:
def solve (P, L, U, b):
    y=np.linalg.solve (L, np.dot(b,P))
    x=np.linalg.solve (U, y)
    return x
def LU(A, b):
    P,L,U=scipy.linalg.lu(A)
    x=solve(P, L, U, b)
# x=np.fft.fft(b_A) Fast Fourier Transformation


#from the Übung: Gauss method
def back_substitution (A, b):
    n=A.shape[0]
    x=np.zeros((n,1))
    for row in range(n-1, -1, -1):
        x[row]= (b[row]-(A[row,row+1:] @ x[row+1:])) / A[row,row]
    return x
def forward_elimination (A, b): #bring [A b] into a triangular form
    n=A.shape[0]
    B=np.hstack((A,b.reshape((n,1))))
    #piv=pivot(B, n)
    for row in range(0, n-1):
        for i in range(row+1, n):
            factor=B[i,row]/B[row,row]
            B[i,row:]-=factor*B[row,row:]
        print("B=\n", B)
    return B[:,:-1], B[:,-1] #A as a triangle and b
def gauss(A, b):
    if any(np.diag(A)==0):
        raise ZeroDevisionError(('Division by zero will occur; pivoting currently not supported'))
    A,b=forward_elimination(A,b)
    return back_substitution(A,b)

N8

Chi squared

In [8]:
# defniere y(p,t)
def y(p,t):
    a=p[1]*np.cos(p[0]*t+p[3])*np.exp(-p[2]*t)
    return a

# definiere chi2N(p,t,y_mess,sigma)
def chi2N(p,t,y_mess,sigma):
    N=len(y_mess)
    a,b=0,0
    for i in range(N):
        a+=y_mess[i]*y(p,t[i])
        b+=y(p,t[i])**2
    s=1
    chi2=0
    for i in range(N):
        chi2+=(y_mess[i]-s*y(p,t[i]))**2
        #print("1"
    chi2/=sigma**2
    return chi2/N
#or
def chi2N2(p,t,y_mess,sigma):
    n=len(y_mess)
    chi=np.zeros(n)
    i=0
    s0=np.zeros(n)
    y0=np.zeros(n)
    for i in range (0,n):
        s0[i]=y_mess[i]*y(p,t[i])
        y0[i]=y(p,t[i])**2
    s=np.sum(s0)/np.sum(y0)
    for i in  range(0,n):
        f=y(p,t[i])
        c=(y_mess[i]-s*f)**2/sigma**2
        chi[i]=c
    chi2=np.sum(chi)/n
    return chi2
#or
def chi2N3(p,t,y_mess,sigma):
    z=(y_mess-y(p,t))**2/sigma**2
    return sum(z)/len(y_mess)

# definiere gradChi2N(p,t,y_mess,sigma)
def gradChi2N(p,t,y_mess,sigma):
    w, y0, gamma, fi=p
    N=len(t)
    a=2*(-y_mess+y(p,t))/(sigma**2)
    dw=np.sum(a*(-y0*np.exp(-gamma*t)*t*np.sin(w*t+fi)))/N
    dy0=np.sum(a*(np.exp(-gamma*t)*np.cos(w*t+fi)))/N
    dgamma=np.sum(a*(-y0*np.exp(-gamma*t)*t*np.cos(w*t+fi)))/N
    dfi=np.sum(a*(-y0*np.exp(-gamma*t)*np.sin(w*t+fi)))/N
    return np.array([dw, dy0, dgamma, dfi])

N9

In [9]:
def diff1_1D(f,dx,Nstuetz):
    dx      = f[1]-f[0]  # Pixelgröße
    Nlinks  = int(np.ceil((Nstuetz-1)/2))
    Nrechts = Nstuetz-Nlinks-1
    N       = len(f)
    d=1
    u=[]
    print(dx)
    for zu in f:
        u.append(dx)
   # M, divisor, h = generiereAbleitung(Nlinks,Nrechts)
    M, divisor, h = generiereAbleitung(0,Nstuetz-1)
    
    pizza=1/dx * M
    H = np.diag(u)
    """
    for j in range(Nlinks,N-Nlinks):
        for l in range(-Nlinks,Nrechts+1):
            H[j,j+l] -= (1/dx)*M[d,l+Nlinks]/(divisor/ssp.factorial(d))
    """
    for j in range(Nlinks,N-Nlinks):
        for l in range(-Nlinks,Nrechts+1):
            H[j,j+l] -= (1/dx)*M[d,l+Nlinks]/(divisor/ssp.factorial(d))
    
    return H.dot(f)

def yStrich(y,x,k,alpha,R,Estart):
    mhbar2 = 2 #*m/(hbar**2)
    dydx=[y[1],mhbar2*(V(x,k,alpha,R)-Estart)*y[0]]
    return dydx

def berechneEigenenergien(Estart,k,alpha,R,N,plotFlag = 0):
    hbar  = 1.       
    m = 1
    mhbar2 = 2*m/(hbar**2)
    x  = np.linspace(0,2*R,N)
    dx = x[1]-x[0]
    y0 = [0,0.1]
    def jaja(eStart):
        x  = np.linspace(0,2*R,N)
        dx = x[1]-x[0]
        y0 = [0,0.1]
        y = si.odeint(yStrich,y0,x,args=(k,alpha,R,eStart))
        #print(y)
        #psi[i]=y[N-1][0]
        return y[N-1][0]

    Efit = so.fsolve(jaja,Estart)              
    return Efit

N10